INSERT INTO USERSEC (USR_ID, USR_FNAME, USR_LNAME, USR_PWD, USR_TYPE)
VALUES ('DEMOUSER', 'Demo', 'User', 'PASS1234', 'U');

INSERT INTO USERSEC (USR_ID, USR_FNAME, USR_LNAME, USR_PWD, USR_TYPE)
VALUES ('ADMIN01', 'Admin', 'User', 'ADMINPWD', 'A');
